services:

  tas-user-service:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: tas-user-service
    ports:
      - 8081:8080
    networks:
      - backend

networks:
  backend:
    external: true
